package com.yw.domain;
// Generated Oct 28, 2015 4:17:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Cuisine generated by hbm2java
 */
public class Cuisine implements java.io.Serializable {

	private Integer cid;
	private Users users;
	private String name;
	private String image;
	private Set types = new HashSet(0);
	private Set containses = new HashSet(0);
	private Set stepses = new HashSet(0);

	public Cuisine() {
	}

	public Cuisine(String name) {
		this.name = name;
	}

	public Cuisine(Users users, String name, String image, Set types, Set containses, Set stepses) {
		this.users = users;
		this.name = name;
		this.image = image;
		this.types = types;
		this.containses = containses;
		this.stepses = stepses;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Set getTypes() {
		return this.types;
	}

	public void setTypes(Set types) {
		this.types = types;
	}

	public Set getContainses() {
		return this.containses;
	}

	public void setContainses(Set containses) {
		this.containses = containses;
	}

	public Set getStepses() {
		return this.stepses;
	}

	public void setStepses(Set stepses) {
		this.stepses = stepses;
	}

}
