package com.yw.domain;
// Generated Oct 28, 2015 4:17:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Ingredients generated by hbm2java
 */
public class Ingredients implements java.io.Serializable {

	private Integer iid;
	private String name;
	private Set containses = new HashSet(0);

	public Ingredients() {
	}

	public Ingredients(String name) {
		this.name = name;
	}

	public Ingredients(String name, Set containses) {
		this.name = name;
		this.containses = containses;
	}

	public Integer getIid() {
		return this.iid;
	}

	public void setIid(Integer iid) {
		this.iid = iid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getContainses() {
		return this.containses;
	}

	public void setContainses(Set containses) {
		this.containses = containses;
	}

}
