package com.yw.domain;
// Generated Oct 28, 2015 4:17:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Steps generated by hbm2java
 */
public class Steps implements java.io.Serializable {

	private Integer sid;
	private Cuisine cuisine;
	private String description;
	private String image;

	public Steps() {
	}

	public Steps(Cuisine cuisine, String description) {
		this.cuisine = cuisine;
		this.description = description;
	}

	public Steps(Cuisine cuisine, String description, String image) {
		this.cuisine = cuisine;
		this.description = description;
		this.image = image;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public Cuisine getCuisine() {
		return this.cuisine;
	}

	public void setCuisine(Cuisine cuisine) {
		this.cuisine = cuisine;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
