package com.yw.domain;
// Generated Oct 28, 2015 4:17:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Type generated by hbm2java
 */
public class Type implements java.io.Serializable {

	private Integer tid;
	private Cuisine cuisine;
	private String name;

	public Type() {
	}

	public Type(Cuisine cuisine, String name) {
		this.cuisine = cuisine;
		this.name = name;
	}

	public Integer getTid() {
		return this.tid;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

	public Cuisine getCuisine() {
		return this.cuisine;
	}

	public void setCuisine(Cuisine cuisine) {
		this.cuisine = cuisine;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
