package com.yw.domain;
// Generated Oct 28, 2015 4:17:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer uid;
	private String name;
	private String password;
	private String avatar;
	private Date birthday;
	private String gender;
	private Set cuisines = new HashSet(0);

	public Users() {
	}

	public Users(String name, String password, String gender) {
		this.name = name;
		this.password = password;
		this.gender = gender;
	}

	public Users(String name, String password, String avatar, Date birthday, String gender, Set cuisines) {
		this.name = name;
		this.password = password;
		this.avatar = avatar;
		this.birthday = birthday;
		this.gender = gender;
		this.cuisines = cuisines;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Set getCuisines() {
		return this.cuisines;
	}

	public void setCuisines(Set cuisines) {
		this.cuisines = cuisines;
	}

}
